version: '3.9'

services:
  osnap-app-receiver:
  
    container_name: osnap-app-receiver
    ports:
    - 8005:8005
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8005", "--reload" ]
    env_file: .env.receiver
    volumes:
      - .:/app
    networks:
      osnap:
  receiver-redis-stack:
    container_name: receiver-redis-stack 
    restart: always
    ports:
      - 6375:6379
      - 8006:8001
    image: redis/redis-stack:latest # redis/redis-stack-server:latest for prod
    command: ["redis-server", "--requirepass", "redis-stack", "--loadmodule", "/opt/redis-stack/lib/redisearch.so", "--loadmodule", "/opt/redis-stack/lib/rejson.so"]
    volumes: 
      - cache:/data
      - redis:/var/lib/redis
    networks:
      osnap:
volumes:
  cache:
    driver: local
  redis:
  
networks:
  osnap:
    external: true