export const SET_FIRST_START = 'SET_FIRST_START'

export const OPEN_FILE_UPLOAD_DIALOG = 'OPEN_FILE_UPLOAD_DIALOG'
export const CLOSE_FILE_UPLOAD_DIALOG = 'CLOSE_FILE_UPLOAD_DIALOG'

export const SET_CONFIG_ITEM = 'SET_CONFIG_ITEM'

export const SHOW_AGENT_CONFIG_DRAWER = 'SHOW_AGENT_CONFIG_DRAWER'
export const HIDE_AGENT_CONFIG_DRAWER = 'HIDE_AGENT_CONFIG_DRAWER'

export const SET_AGENT_INIT_STATE = 'SET_AGENT_INIT_STATE'
export const SAVE_AGENT_STATE = 'SAVE_AGENT_STATE'
export const RESTORE_AGENT_STATE = 'RESTORE_AGENT_STATE'
export const APPEND_WEBSOCKET_MESSAGES = 'APPEND_WEBSOCKET_MESSAGES'

export const SET_WEBSOCKET = 'SET_WEBSOCKET'
export const SET_WEBSOCKET_CONNECTED = 'SET_WEBSOCKET_CONNECTED'
export const SET_WEBSOCKET_DISCONNECTED = 'SET_WEBSOCKET_DISCONNECTED'
export const CLEAR_WEBSOCKET_MESSAGES = 'CLEAR_WEBSOCKET_MESSAGES'

export const UPDATE_CYCLE_COUNT = 'UPDATE_CYCLE_COUNT'
export const UPDATE_AGENT_CYCLE_STATE = 'UPDATE_AGENT_CYCLE_STATE'
